# Libraries

In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Loading data

In [37]:
path = 'djia29/AAPL.csv'

with open(path, 'r') as f:
    data_raw = pd.read_csv(f, index_col='date', parse_dates=['date'], skiprows = [1])

data_raw.head()

             close      volume    open     high     low
date
2018-08-13  208.87  25864510.0  207.70  210.952  207.70
2018-08-10  207.53  24592460.0  207.36  209.100  206.67
2018-08-09  208.88  23389530.0  207.28  209.780  207.20
2018-08-08  207.25  22493750.0  206.05  207.810  204.52
2018-08-07  207.11  25525650.0  209.32  209.500  206.76

In [46]:
data = data_raw.copy()

data = data.astype(float)
data = data.sort_index(ascending=True)

data.head()

              close       volume     open     high      low
date
2008-08-14  25.6171  177684343.0  25.4757  25.7786  25.4057
2008-08-15  25.1057  176996663.0  25.5771  25.6786  25.0071
2008-08-18  25.0557  137832351.0  25.0814  25.4014  24.8314
2008-08-19  24.7900  153915766.0  24.9343  25.2957  24.5443
2008-08-20  25.1200  126718798.0  24.9676  25.2771  24.8014

In [48]:
data['returns'] = data['close'].pct_change()
data['log_returns'] = np.log(data['close'] / data['close'].shift(1))
data.head()

,close,volume,open,high,low,returns,log_returns
date,,,,,,,
2008-08-14,25.6171,177684343.0,25.4757,25.7786,25.4057,NaN,NaN
2008-08-15,25.1057,176996663.0,25.5771,25.6786,25.0071,-0.019963,-0.020165
2008-08-18,25.0557,137832351.0,25.0814,25.4014,24.8314,-0.001992,-0.001994
2008-08-19,24.7900,153915766.0,24.9343,25.2957,24.5443,-0.010604,-0.010661
2008-08-20,25.1200,126718798.0,24.9676,25.2771,24.8014,0.013312,0.013224